/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.yqlabs.bluetoothchat;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f040001;
        public static final int light=0x7f040004;
        public static final int rbm_item_text_color=0x7f040003;
        public static final int rbm_menu_background=0x7f040002;
        public static final int white=0x7f040000;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
        public static final int bg=0x7f020001;
        public static final int circle=0x7f020002;
        public static final int circle1=0x7f020003;
        public static final int circle_green=0x7f020004;
        public static final int circle_red=0x7f020005;
        public static final int circle_start=0x7f020006;
        public static final int circle_start1=0x7f020007;
        public static final int circle_stop=0x7f020008;
        public static final int ic_launcher=0x7f020009;
    }
    public static final class id {
        public static final int button_scan=0x7f090006;
        public static final int button_send=0x7f090008;
        public static final int discoverable=0x7f09000a;
        public static final int new_devices=0x7f090005;
        public static final int paired_devices=0x7f090003;
        public static final int scan=0x7f090009;
        public static final int texview=0x7f090007;
        public static final int title_left_text=0x7f090000;
        public static final int title_new_devices=0x7f090004;
        public static final int title_paired_devices=0x7f090002;
        public static final int title_right_text=0x7f090001;
    }
    public static final class layout {
        public static final int custom_title=0x7f030000;
        public static final int device_list=0x7f030001;
        public static final int device_name=0x7f030002;
        public static final int main=0x7f030003;
        public static final int message=0x7f030004;
    }
    public static final class menu {
        public static final int option_menu=0x7f080000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int bt_not_enabled_leaving=0x7f060003;
        public static final int button_scan=0x7f06000d;
        /**  Options Menu 
         */
        public static final int connect=0x7f06000e;
        public static final int discoverable=0x7f06000f;
        public static final int none_found=0x7f06000a;
        public static final int none_paired=0x7f060009;
        public static final int not_connected=0x7f060002;
        /**  DeviceListActivity 
         */
        public static final int scanning=0x7f060007;
        public static final int select_device=0x7f060008;
        /**  BluetoothChat 
         */
        public static final int send=0x7f060001;
        public static final int title_connected_to=0x7f060005;
        public static final int title_connecting=0x7f060004;
        public static final int title_not_connected=0x7f060006;
        public static final int title_other_devices=0x7f06000c;
        public static final int title_paired_devices=0x7f06000b;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
    }
}
